### ISSUE TITLE
the list of individuals who donated seems truncated 

### ISSUE THREAD

**Issue by carolinagc** [rails-girls-summer-of-code/summer-of-code-2014#55] opened 2013-06-10 15:00 UTC
In twitter @jlsuttles says:
@RailsGirlsSoC the list of individuals who donated seems truncated railsgirlssummerofcode.org/campaign/

**Comment by jmentz** [comment] 2013-06-10 15:09
The list is paginated, but the pagination is shown only above the list of donations.
We should display the pagination links also below the list.
I can do that in about two hours when i am back at home.

**Comment by finnp** [comment] 2013-06-10 17:30
The comment probably referred to the same problem as in #56. Should be fixed through #57

**Comment by unicornzero** [comment] 2013-06-24 22:56
I hope my pull request addresses this issue. Please let me know if I missed something.
-Rylee

**Comment by unicornzero** [comment] 2013-06-25 20:10
Pagination buttons are now at the bottom of the page, but there is an issue (in the jQuery, I believe) causing the screen to sometimes scroll when a pagination link is clicked. Further discussion is here: https://github.com/rails-girls-summer-of-code/summer-of-code/pull/80

**Comment by svenfuchs** [comment] 2013-06-26 09:25
awesome work, @unicornzero 

i think i don't have time to look into the click event thing myself, but it might be worth trying to use `event.preventDefault()`: http://api.jquery.com/event.preventDefault

You could try to change these lines https://github.com/rails-girls-summer-of-code/summer-of-code/blob/gh-pages/js/pagination.js#L18-L20 like so:

```
      return $('a.' + key, _this.element).click(function(event) {
        event.preventDefault();
        return _this.onClick(key);
      });
```

**Comment by unicornzero** [comment] 2013-06-26 23:43
I wasn't able to get to that today; it is on my list of tasks for tomorrow, though! Thanks for the pointer. Hopefully that will help me get some traction on the issue.

**Comment by lislis** [comment] 2013-06-27 12:52
This is working now, or am I overseeing something?

**Comment by unicornzero** [comment] 2013-06-27 19:10
@lislis if you load the Campaign page, scroll to the bottom of the donors table, and click the Next link there, I expect you will have automatically scrolled down the page and be viewing the footer.

**Comment by unicornzero** [comment] 2013-06-27 19:13
I implemented the solution that @svenfuchs suggested, but the problem persisted. I have attempted to troubleshoot and wasn't able to make any progress. I have little to no jquery experience, so further troubleshooting this issue is far above my knowledge level at present. I'd like to pass this on to someone else, as I don't know how long it will be until I have the skills to be able to fix this problem.

What's the best way to proceed? Leave this Issue open as is, or create a separate issue for this problem?

**Comment by svenfuchs** [comment] 2013-06-29 14:31
@unicornzero i've had a look at this, and the suggestions i gave actually were a red herring.

The issue was not only that it triggered the default action, but also that it removed the entire list, and then inserted a new one. It even did that twice. So the browser tried to keep the current scroll position and because the whole thing took too long it ended up further down on the page.

I've fixed a few things around that and now it looks better, not perfect, but ok, I guess.

https://github.com/rails-girls-summer-of-code/summer-of-code/commit/0871cdd3b59ce7cbe5f095006ff138f1a32a2f55

Thanks for looking into this @unicornzero! And sorry about the wrong hints :/

**Closed as completed by svenfuchs** 2013-06-29 14:31 UTC

**Comment by unicornzero** [comment] 2013-06-29 17:35
@svenfuchs Oh, wow. Thanks so much for the follow-up. Though I am a total novice with jQuery, I was pretty frustrated that I couldn't begin to wrap my head around the cause of the behavior I was seeing. Now that you've described what was happening, I see why it eluded me. I'm so glad you were able to identify the issue.
